### PR TITLE
Fix `get_fee_rate_statics` param, Fix `cargo-deny` installation, Fix CI `test_get_indexer_tip`

### LINKED ISSUE #83: The correct parameter name should be target instead of tartet
Correct the parameter name to target as per the CKB/RPC documentation:

- https://github.com/nervosnetwork/ckb-sdk-rust/blob/master/src/rpc/ckb.rs#L42
- https://github.com/eval-exec/ckb-sdk-rust/blob/exec/data2/src/rpc/ckb.rs#L44C3-L44C3
- https://github.com/eval-exec/ckb-sdk-rust/blob/exec/data2/src/rpc/ckb.rs#L43

The correct parameter name should be target instead of tartet, following the CKB/RPC documentation:

- https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-get_fee_rate_statics

### PR DESCRIPTION
**Pull request by eval-exec**
close #83

### CODE REVIEW

**Comment by eval-exec** [comment]
@quake I think this PR is ready for merge.

**Comment by quake** [comment]
there is a CI error:
```
Caused by:
  package `cargo-deny v0.14.0` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.67.1
```

could you help to fix it?

**Comment by eval-exec** [comment]
@quake Could you please re-trigger the CI action so I can verify that my fix works?

**Comment by eval-exec** [comment]
`    tests::ckb_indexer_rpc::test_get_indexer_tip` failed, fixing...

**Pull request merged**
